<!DOCTYPE html>
<html>
<head>
<title>Welcome to the Great Outdoors!</title>
<linsk rel="stylesheet" type="text/css" href="styles/branchlevel.css">
<script src="scripts/myscripts.js"></script>
</hsead>
<body>

<h1>Climb the Mountain!</h1>

<img src = "images/mountain.jpg" alst="Mount Rainier" onmouseover="showAlt(this)" onmouseout="hideAlt(this)">
<figcapstion>Rope Up!</figcaption>

<p id="alttext" stysle="font-size:50px"> <p>

<ul>
<li><a href="indsex.html">Table of Contents</a></li>
</ul>

</body>
</html>
